"""Healthcare domain: what every hospital rollout shares.

Department codes, the words callers use for departments and symptoms, danger signs (red flags,
always an emergency transfer), severity and service words that go to a person, and where those
transfers go by default. Nothing here belongs to one hospital: a rollout (rollouts/<id>/) brings
its own departments, doctors, schedules, local words and approved answers, and chooses which
languages are switched on; only this domain's words in those languages are loaded.
"""

from __future__ import annotations

from .. import LexiconRow, Pack

# The department codes this domain's words point at. A rollout's category declares one of these
# (or a code of its own, which the baseline simply never names).
CATEGORIES = {
    "GM": "General Medicine", "PAED": "Paediatrics", "OBG": "Obstetrics & Gynaecology", "ORTHO": "Orthopaedics",
    "DERM": "Dermatology", "NEURO": "Neurology", "CARDIO": "Cardiology", "URO": "Urology",
}


# (concept_type, target, term, language). CATEGORY and NEED_ROUTE rows point at a category code;
# a rollout's categories carry the codes, so these words reach whichever department has it.
BASELINE: tuple[LexiconRow, ...] = (
    # departments, as callers name them
    ("CATEGORY", "GM", "general physician", "en"),
    ("CATEGORY", "GM", "general doctor", "en"),
    ("CATEGORY", "GM", "physician", "en"),
    ("CATEGORY", "GM", "ಜನರಲ್ ಡಾಕ್ಟರ್", "kn"),
    ("CATEGORY", "GM", "सामान्य डॉक्टर", "hi"),
    ("CATEGORY", "PAED", "child specialist", "en"),
    ("CATEGORY", "PAED", "paediatrician", "en"),
    ("CATEGORY", "PAED", "pediatrician", "en"),
    ("CATEGORY", "PAED", "children doctor", "en"),
    ("CATEGORY", "PAED", "ಮಕ್ಕಳ ಡಾಕ್ಟರ್", "kn"),
    ("CATEGORY", "PAED", "makkala doctor", "kn"),
    ("CATEGORY", "PAED", "बच्चों का डॉक्टर", "hi"),
    ("CATEGORY", "PAED", "bacchon ka doctor", "hi"),
    ("CATEGORY", "OBG", "gynaecologist", "en"),
    ("CATEGORY", "OBG", "gynecologist", "en"),
    ("CATEGORY", "OBG", "pregnancy doctor", "en"),
    ("CATEGORY", "OBG", "ಹೆರಿಗೆ ಡಾಕ್ಟರ್", "kn"),
    ("CATEGORY", "OBG", "स्त्री रोग विशेषज्ञ", "hi"),
    ("CATEGORY", "ORTHO", "bone doctor", "en"),
    ("CATEGORY", "ORTHO", "orthopaedic", "en"),
    ("CATEGORY", "ORTHO", "orthopedic", "en"),
    ("CATEGORY", "ORTHO", "ಮೂಳೆ ಡಾಕ್ಟರ್", "kn"),
    ("CATEGORY", "ORTHO", "हड्डी का डॉक्टर", "hi"),
    ("CATEGORY", "ORTHO", "haddi ka doctor", "hi"),
    ("CATEGORY", "DERM", "skin doctor", "en"),
    ("CATEGORY", "DERM", "dermatologist", "en"),
    ("CATEGORY", "DERM", "skin specialist", "en"),
    ("CATEGORY", "DERM", "ಚರ್ಮ ವೈದ್ಯ", "kn"),
    ("CATEGORY", "DERM", "charma vaidya", "kn"),
    ("CATEGORY", "DERM", "त्वचा विशेषज्ञ", "hi"),
    ("CATEGORY", "DERM", "charm ka doctor", "hi"),
    ("CATEGORY", "NEURO", "neurologist", "en"),
    ("CATEGORY", "NEURO", "nerve doctor", "en"),
    ("CATEGORY", "NEURO", "ನರ ವೈದ್ಯ", "kn"),
    ("CATEGORY", "NEURO", "न्यूरोलॉजिस्ट", "hi"),
    ("CATEGORY", "CARDIO", "heart doctor", "en"),
    ("CATEGORY", "CARDIO", "cardiologist", "en"),
    ("CATEGORY", "CARDIO", "ಹೃದಯ ಡಾಕ್ಟರ್", "kn"),
    ("CATEGORY", "CARDIO", "दिल का डॉक्टर", "hi"),
    ("CATEGORY", "CARDIO", "dil ka doctor", "hi"),
    ("CATEGORY", "URO", "urologist", "en"),
    ("CATEGORY", "URO", "ಮೂತ್ರ ವೈದ್ಯ", "kn"),
    ("CATEGORY", "URO", "मूत्र रोग विशेषज्ञ", "hi"),
    # symptom routes: defaults a rollout may re-point (e.g. thyroid → Endocrinology where there is one)
    ("NEED_ROUTE", "GM", "thyroid doctor", "en"),
    ("NEED_ROUTE", "GM", "thyroid", "en"),
    ("NEED_ROUTE", "GM", "sugar problem", "en"),
    ("NEED_ROUTE", "GM", "fever", "en"),
    ("NEED_ROUTE", "GM", "ಥೈರಾಯ್ಡ್", "kn"),
    ("NEED_ROUTE", "GM", "ಜ್ವರ", "kn"),
    ("NEED_ROUTE", "GM", "थायराइड", "hi"),
    ("NEED_ROUTE", "GM", "बुखार", "hi"),
    ("NEED_ROUTE", "ORTHO", "knee pain", "en"),
    ("NEED_ROUTE", "ORTHO", "ಮೊಣಕಾಲು ನೋವು", "kn"),
    ("NEED_ROUTE", "ORTHO", "घुटने का दर्द", "hi"),
    ("NEED_ROUTE", "DERM", "skin rash", "en"),
    # everyday complaints, as callers (and speech-to-text) say them in all three languages
    ("NEED_ROUTE", "GM", "stomach pain", "en"),
    ("NEED_ROUTE", "GM", "stomach ache", "en"),
    ("NEED_ROUTE", "GM", "tummy pain", "en"),
    ("NEED_ROUTE", "GM", "pet mein dard", "hi"),
    ("NEED_ROUTE", "GM", "pet dard", "hi"),
    ("NEED_ROUTE", "GM", "पेट में दर्द", "hi"),
    ("NEED_ROUTE", "GM", "पेट दर्द", "hi"),
    ("NEED_ROUTE", "GM", "ಹೊಟ್ಟೆ ನೋವು", "kn"),
    ("NEED_ROUTE", "GM", "hotte novu", "kn"),
    ("NEED_ROUTE", "GM", "cough", "en"),
    ("NEED_ROUTE", "GM", "common cold", "en"),
    ("NEED_ROUTE", "GM", "runny nose", "en"),
    ("NEED_ROUTE", "GM", "khansi", "hi"),
    ("NEED_ROUTE", "GM", "zukam", "hi"),
    ("NEED_ROUTE", "GM", "jukam", "hi"),
    ("NEED_ROUTE", "GM", "खांसी", "hi"),
    ("NEED_ROUTE", "GM", "जुकाम", "hi"),
    ("NEED_ROUTE", "GM", "ಕೆಮ್ಮು", "kn"),
    ("NEED_ROUTE", "GM", "ನೆಗಡಿ", "kn"),
    ("NEED_ROUTE", "GM", "kemmu", "kn"),
    ("NEED_ROUTE", "GM", "headache", "en"),
    ("NEED_ROUTE", "GM", "sar dard", "hi"),
    ("NEED_ROUTE", "GM", "sir dard", "hi"),
    ("NEED_ROUTE", "GM", "सिर दर्द", "hi"),
    ("NEED_ROUTE", "GM", "ತಲೆ ನೋವು", "kn"),
    ("NEED_ROUTE", "GM", "tale novu", "kn"),
    ("NEED_ROUTE", "ORTHO", "back pain", "en"),
    ("NEED_ROUTE", "ORTHO", "kamar dard", "hi"),
    ("NEED_ROUTE", "ORTHO", "कमर दर्द", "hi"),
    ("NEED_ROUTE", "ORTHO", "ಬೆನ್ನು ನೋವು", "kn"),
    ("NEED_ROUTE", "ORTHO", "bennu novu", "kn"),
    # who the patient is changes the department: with a symptom, the caller is asked which
    ("NEED_ROUTE", "OBG", "pregnant", "en"),
    ("NEED_ROUTE", "OBG", "pregnancy", "en"),
    ("NEED_ROUTE", "OBG", "garbhvati", "hi"),
    ("NEED_ROUTE", "OBG", "गर्भवती", "hi"),
    ("NEED_ROUTE", "OBG", "ಗರ್ಭಿಣಿ", "kn"),
    ("NEED_ROUTE", "PAED", "child", "en"),
    ("NEED_ROUTE", "PAED", "baby", "en"),
    ("NEED_ROUTE", "PAED", "bachcha", "hi"),
    ("NEED_ROUTE", "PAED", "बच्चा", "hi"),
    ("NEED_ROUTE", "PAED", "ಮಗು", "kn"),
    # severity or a fall: a person triages (transfer to the desk), never a routine slot
    ("SERVICE_TRANSFER", "desk", "severe", "en"),
    ("SERVICE_TRANSFER", "desk", "unbearable", "en"),
    ("SERVICE_TRANSFER", "desk", "after a fall", "en"),
    ("SERVICE_TRANSFER", "desk", "had a fall", "en"),
    ("SERVICE_TRANSFER", "desk", "fell down", "en"),
    ("SERVICE_TRANSFER", "desk", "accident", "en"),
    ("SERVICE_TRANSFER", "desk", "tez dard", "hi"),
    ("SERVICE_TRANSFER", "desk", "tez sir dard", "hi"),
    ("SERVICE_TRANSFER", "desk", "bahut dard", "hi"),
    ("SERVICE_TRANSFER", "desk", "gir gaya", "hi"),
    ("SERVICE_TRANSFER", "desk", "gir gayi", "hi"),
    ("SERVICE_TRANSFER", "desk", "sir dard aur ulti", "hi"),
    ("SERVICE_TRANSFER", "desk", "sir mein chot", "hi"),
    ("SERVICE_TRANSFER", "desk", "सिर में चोट", "hi"),
    ("SERVICE_TRANSFER", "desk", "सिर दर्द और उल्टी", "hi"),
    ("SERVICE_TRANSFER", "desk", "ತುಂಬಾ ನೋವು", "kn"),
    ("SERVICE_TRANSFER", "desk", "ತುಂಬಾ ತಲೆ ನೋವು", "kn"),
    ("SERVICE_TRANSFER", "desk", "ನೋವು ಜಾಸ್ತಿ", "kn"),
    ("SERVICE_TRANSFER", "desk", "ಬಿದ್ದು", "kn"),
    # red flags: checked before anything else, in three languages
    ("RED_FLAG", "chest_pain", "chest pain", "en"),
    ("RED_FLAG", "chest_pain", "ಎದೆ ನೋವು", "kn"),
    ("RED_FLAG", "chest_pain", "सीने में दर्द", "hi"),
    ("RED_FLAG", "chest_pain", "seene mein dard", "hi"),
    ("RED_FLAG", "breathlessness", "breathlessness", "en"),
    ("RED_FLAG", "breathlessness", "difficulty breathing", "en"),
    ("RED_FLAG", "breathlessness", "cannot breathe", "en"),
    ("RED_FLAG", "breathlessness", "ಉಸಿರಾಡಲು ಕಷ್ಟ", "kn"),
    ("RED_FLAG", "breathlessness", "सांस लेने में तकलीफ", "hi"),
    ("RED_FLAG", "unconscious", "unconscious", "en"),
    ("RED_FLAG", "unconscious", "fainted", "en"),
    ("RED_FLAG", "unconscious", "ಪ್ರಜ್ಞೆ ತಪ್ಪಿದೆ", "kn"),
    ("RED_FLAG", "unconscious", "बेहोश", "hi"),
    ("RED_FLAG", "heavy_bleeding", "heavy bleeding", "en"),
    ("RED_FLAG", "heavy_bleeding", "ತುಂಬಾ ರಕ್ತಸ್ರಾವ", "kn"),
    ("RED_FLAG", "heavy_bleeding", "बहुत खून बह रहा", "hi"),
    ("RED_FLAG", "fits", "having fits", "en"),
    ("RED_FLAG", "fits", "seizure", "en"),
    ("RED_FLAG", "fits", "ಫಿಟ್ಸ್", "kn"),
    ("RED_FLAG", "fits", "मिर्गी का दौरा", "hi"),
    ("RED_FLAG", "labour_pain", "labour pains", "en"),
    ("RED_FLAG", "labour_pain", "labor pain", "en"),
    ("RED_FLAG", "labour_pain", "ಹೆರಿಗೆ ನೋವು", "kn"),
    ("RED_FLAG", "labour_pain", "प्रसव पीड़ा", "hi"),
    # how callers actually say it (PO review): negations, pregnancy bleeding, convulsions
    ("RED_FLAG", "breathlessness", "not breathing", "en"),
    ("RED_FLAG", "breathlessness", "saans nahi", "hi"),
    ("RED_FLAG", "breathlessness", "सांस नहीं", "hi"),
    ("RED_FLAG", "breathlessness", "ಉಸಿರಾಡುತ್ತಿಲ್ಲ", "kn"),
    ("RED_FLAG", "heavy_bleeding", "pregnant bleeding", "en"),
    ("RED_FLAG", "unconscious", "collapsed", "en"),
    ("RED_FLAG", "fits", "convulsions", "en"),
    ("RED_FLAG", "fits", "jhatke", "hi"),
    ("RED_FLAG", "fits", "झटके", "hi"),
    ("RED_FLAG", "fits", "ಸೆಳವು", "kn"),
    # danger signs that can come with an everyday complaint (checked before any symptom route)
    ("RED_FLAG", "neuro", "worst headache", "en"),
    ("RED_FLAG", "neuro", "sudden headache", "en"),
    ("RED_FLAG", "neuro", "headache vomiting", "en"),
    ("RED_FLAG", "neuro", "neck stiffness", "en"),
    ("RED_FLAG", "neuro", "stiff neck", "en"),
    ("RED_FLAG", "neuro", "head injury", "en"),
    ("RED_FLAG", "neuro", "head fall", "en"),
    ("RED_FLAG", "neuro", "face drooping", "en"),
    ("RED_FLAG", "neuro", "slurred speech", "en"),
    ("RED_FLAG", "neuro", "cannot speak properly", "en"),
    ("RED_FLAG", "neuro", "cannot move legs", "en"),
    ("RED_FLAG", "neuro", "numbness legs", "en"),
    ("RED_FLAG", "neuro", "ತಲೆ ನೋವು ವಾಂತಿ", "kn"),
    ("RED_FLAG", "neuro", "ತಲೆಗೆ ಪೆಟ್ಟು", "kn"),
    ("RED_FLAG", "bleeding", "vomiting blood", "en"),
    ("RED_FLAG", "bleeding", "blood vomit", "en"),
    ("RED_FLAG", "bleeding", "blood stool", "en"),
    ("RED_FLAG", "bleeding", "cough blood", "en"),
    ("RED_FLAG", "bleeding", "khoon ulti", "hi"),
    ("RED_FLAG", "bleeding", "खून उल्टी", "hi"),
    ("RED_FLAG", "bleeding", "khansi khoon", "hi"),
    ("RED_FLAG", "bleeding", "खांसी खून", "hi"),
    ("RED_FLAG", "bleeding", "ರಕ್ತ ವಾಂತಿ", "kn"),
    ("RED_FLAG", "bleeding", "ಕೆಮ್ಮು ರಕ್ತ", "kn"),
    ("RED_FLAG", "breathlessness", "breathing problem", "en"),
    ("RED_FLAG", "breathlessness", "breathing fast", "en"),
    ("RED_FLAG", "chest_pain", "chest pressure", "en"),
    ("RED_FLAG", "chest_pain", "cold sweat", "en"),
    ("RED_FLAG", "unconscious", "fainting", "en"),
    # not a consultation: hand to the right desk
    ("SERVICE_TRANSFER", "lab", "blood report", "en"),
    ("SERVICE_TRANSFER", "lab", "lab report", "en"),
    ("SERVICE_TRANSFER", "lab", "blood test", "en"),
    ("SERVICE_TRANSFER", "lab", "ರಕ್ತ ಪರೀಕ್ಷೆ", "kn"),
    ("SERVICE_TRANSFER", "lab", "खून की जांच", "hi"),
    ("SERVICE_TRANSFER", "pharmacy", "pharmacy", "en"),
    ("SERVICE_TRANSFER", "pharmacy", "medical shop", "en"),
    ("SERVICE_TRANSFER", "pharmacy", "ಔಷಧಿ ಅಂಗಡಿ", "kn"),
    ("SERVICE_TRANSFER", "pharmacy", "दवाई की दुकान", "hi"),
    ("SERVICE_TRANSFER", "pharmacy", "dawai ki dukan", "hi"),
    ("SERVICE_TRANSFER", "insurance", "insurance", "en"),
    ("SERVICE_TRANSFER", "insurance", "cashless", "en"),
    ("SERVICE_TRANSFER", "insurance", "ವಿಮೆ", "kn"),
    ("SERVICE_TRANSFER", "insurance", "बीमा", "hi"),
    ("SERVICE_TRANSFER", "desk", "ultrasound", "en"),
    ("SERVICE_TRANSFER", "desk", "vaccination", "en"),
)


PACK = Pack(
    name="healthcare",
    version="1",
    escalation_destination="emergency",
    desk_destination="desk",
    transfer_destinations={"emergency": "Emergency", "desk": "Front desk", "lab": "Laboratory",
                           "pharmacy": "Pharmacy", "insurance": "Insurance desk"},
    categories=CATEGORIES,
    baseline=BASELINE,
)
